version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTFRES_PASSWORD: root
      POSTGRES_DB: library_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app_todo
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  
volumes:
  postgres_data: